docs_dir: Docs
repo_url: https://github.com/arthurlleite/2025.1-CelularSeguro
repo_name: 2025.1-Celular Seguro

site_name: Celular Seguro

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Landing Page: landing.html
  - Home: index.md

  - Atas:
    - Sprint 1:
        - Ata 1: "atas-reuniao/sprint-1/ata-reuniao-1.md"
        - Ata 2: "atas-reuniao/sprint-1/ata-reuniao-2.md"
        - Ata 3: "atas-reuniao/sprint-1/ata-reuniao-3.md"
        - Ata 4: "atas-reuniao/sprint-1/ata-reuniao-4.md"
    - Sprint 2:
        - Ata 1: "atas-reuniao/sprint-2/ata-reuniao-5.md"
    - Sprint 3:
        - Ata 1: "atas-reuniao/sprint-2/ata-reuniao-6.md"
    - Sprint 4:
        - Ata 1: "atas-reuniao/sprint-4/ata-reuniao-7.md"
    - Sprint 5:
        - Ata 1: "atas-reuniao/sprint-5/ata-reuniao-8.md"

  - Planejamento: 
      - Introdução: "documento-planejamento/documento-planejamento.md"
      - HeatMap: "documento-planejamento/heatmap.md"
      - Cronograma Planejado: "documento-planejamento/cronograma-planejado.md"
      - Cronograma Executado: "documento-planejamento/cronograma-executado.md"
      - Ferramentas: "documento-planejamento/ferramentas-utilizadas.md"
      - Metodologia: "documento-planejamento/metodologias-utilizadas.md"

  - Pré-Rastreabilidade:
      - Introdução: "documento-pre-rastreabilidade/documento-pre-rastreabilidade.md"
      - Aplicativos Analisados: "documento-pre-rastreabilidade/aplicativos_analisados.md"
      - Aplicativo Selecionado: "documento-pre-rastreabilidade/aplicativo_selecionado.md"

  - Elicitação:
    - Introdução: "documento-elicitacao/Introducao.md"
    - Perfil do Usuário: "documento-elicitacao/PerfilUsuario.md"
    - Personas: "documento-elicitacao/Personas.md"
    - Técnicas de Elicitação:
        - Análise de Documentos: "documento-elicitacao/AnalisedeDocumentos.md"
        - Questionário: "documento-elicitacao/Questionario.md"
        - Brainstorming: "documento-elicitacao/Brainstorming.md"
        - Storytelling: "documento-elicitacao/Storytelling.md"
        - Observação: "documento-elicitacao/Observacao.md"
        - Requisitos Elicitados: "documento-elicitacao/requisitos_elicitados.md"
    - Técnicas de Priorização:
        - First Thing First: "documento-elicitacao/FirstThingFirst.md"
        - QFD: "documento-elicitacao/QFD.md"
        - MoSCoW: "documento-elicitacao/MoSCoW.md"
        - $100: "documento-elicitacao/100.md"

  - Modelagem:
      - Casos de Uso: "documento-modelagem/caso-de-uso.md"
      - Léxicos: "documento-modelagem/lexico.md"
      - Cenários: "documento-modelagem/cenario.md"
      - Especificação Suplementar: "documento-modelagem/especificacoes-suplementar.md"

      - Agil:
          - NFR Framework: "documento-modelagem/Agil/NR_Framework.md"
          - Backlog: "documento-modelagem/Agil/Backlog.md"
          - Histórias de usuário: "documento-modelagem/Agil/Historias_de_usuario.md"

  - Pós-Rastreabilidade:
      - Matriz Geral: "documento-rastreabilidade/matriz.md"
      - Pós-Rastreabilidade: "documento-rastreabilidade/pos-rastreabilidade.md"

    
  - Verificação:
      - Introducão: "documento-verificacao/introducao-verificacao.md"
      - Planejamento Geral: "documento-verificacao/introducao-planejamento.md"
      - Entregas:
        - Entrega 1: 
          - Planejamento Entrega 1: "documento-verificacao/Entregas/Entrega-1/planejamento-entrega1.md"
          - Verificação 1: "documento-verificacao/Entregas/Entrega-1/documento-verificacao-grupo.md"
        - Entrega 2: 
          - Planejamento Entrega 2: "documento-verificacao/Entregas/Entrega-2/planejamento-entrega2.md"
          - Verificação 2: "documento-verificacao/Entregas/Entrega-2/documento-verificacao-grupo2.md"
        - Entrega 3: 
          - Planejamento Entrega 3: "documento-verificacao/Entregas/Entrega-3/planejamento-entrega3.md"
          - Verificação 3: "documento-verificacao/Entregas/Entrega-3/documento-verificacao-grupo3.md"
        - Entrega 4: 
          - Planejamento Entrega 4: "documento-verificacao/Entregas/Entrega-4/planejamento-entrega4.md"
          - Verificação 4: "documento-verificacao/Entregas/Entrega-4/documento-verificacao-grupo4.md"
        - Entrega 5: 
          - Planejamento Entrega 5: "documento-verificacao/Entregas/Entrega-5/planejamento-entrega5.md"
          - Verificação 5: "documento-verificacao/Entregas/Entrega-5/documento-verificacao-grupo5.md"
        - Entrega 6:
          - Planejamento Entrega 5: "documento-verificacao/Entregas/Entrega-6/planejamento-entrega6.md"
          - Verificação 6: "documento-verificacao/Entregas/Entrega-6/documento-verificacao-grupo6.md"
            

  - Validação:
      - Prototipação: "documento-validacao/documento-prototipacao.md"
      - Artefatos Inconformes 1: "documento-validacao/documentacao-artefatosAnteriores.md"
      - Comprovação Informal: "documento-validacao/documentacao-resposta-informal.md"

  - Inspeção:
      - Grupo:
        - Entrega 1: "documento-inspecao/grupo/documento_inspecao_grupo.md" 
        - Entrega 2: "documento-inspecao/grupo/documento_inspecao_grupo2.md" 
        - Entrega 3: "documento-inspecao/grupo/documento_inspecao_grupo3.md" 
        - Entrega 4: "documento-inspecao/grupo/documento_inspecao_grupo4.md"
        - Entrega 5: "documento-inspecao/grupo/documento_inspecao_grupo5.md"
        - Entrega 6: "documento-inspecao/grupo/documento_inspecao_grupo6.md"
      - Grupo + 1: 
        - Entrega 1: "documento-inspecao/grupo+1/documento_inspecao_grupo+1.md" 
        - Entrega 2: "documento-inspecao/grupo+1/documento_inspecao_grupo+1-2.md" 
        - Entrega 3: "documento-inspecao/grupo+1/documento_inspecao_grupo+1-3.md" 
        - Entrega 4: "documento-inspecao/grupo+1/documento_inspecao_grupo+1-4.md"
        - Entrega 5: "documento-inspecao/grupo+1/inspecaogrupo+1-5.md"
        - Entrega 6: "documento-inspecao/grupo+1/inspecaogrupo+1-6.md"
      - Inspeção Final Grupo +1: "documento-inspecao/grupo+1/final+1.md"      

  - Apresentação:
    - Apresentações: 
      - Apresentação 1: "documento-apresentacao/apresentacao-1.md" 
      - Apresentação 2: "documento-apresentacao/apresentacao-2.md"
      - Apresentação 3: "documento-apresentacao/apresentacao-3.md"
      - Apresentação 4: "documento-apresentacao/apresentacao-4.md"
      - Apresentação 5: "documento-apresentacao/apresentacao-5.md"
      - Apresentação 6: "documento-apresentacao/apresentacao-6.md"
      - Entrega Final: "documento-apresentacao/entrega-final.md"

  - Entrega Final: 
      - Aplicativo Selecionado: "documento-entrega-final/aplicativo-selecionado.md"  
      - Planejamento de Recursos e das Entregas: "documento-entrega-final/planejamento-recursos.md"  
      - Execução do Projeto: "documento-entrega-final/execucao-projeto.md" 
      - Resultados Alcançados com a Execução do Projeto: "documento-entrega-final/resultados-alcancados.md" 
      - Sintetização das Ferramentas: "documento-entrega-final/sintetizacao-ferramentas.md" 
      - Sintetização das Técnicas: "documento-entrega-final/sintetizacao-tecnicas.md" 
      - Sintetização dos Artefatos: "documento-entrega-final/sintetizacao-artefatos.md" 
      - Sintetização Método de Verificação: "documento-entrega-final/sintetizacao-metodo.md" 
      - Sintetização dos vídeos de Apresentação: "documento-entrega-final/sintetizacao-videos.md" 
      - Facilidades e Dificuldades Encontradas no Projeto: "documento-entrega-final/sintetizacao-facilidades.md" 

theme:
  logo: assets/LogoCelularSeguro.png
  favicon: assets/LogoCelularSeguro.png
  font:
    text: Montserrat
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: #2c2c7c
      accent: #2c2c7c
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/git-alt
